# _config.yml

title: My Project Notes
description: "All of my CCIE Security 6.1 notes"
repository: Quantifiable-Quasar/ccie-notes
url: "https://quantifiable-quasar.github.io"
baseurl: "/ccie-notes"

# This tells GitHub Pages to use the "minima" theme
theme: just-the-docs

search_enabled: true

aux_links:
  "Github Repo":
    - "https://github.com/quantifiable-quasar/ccie-notes"

# These plugins are good defaults for Jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
